### ISSUE TITLE
Could you share the code of dataset?

### ISSUE THREAD

**Issue by chenshen03** [futureisatyourhand/issuses-codes#1]
Thank you for excellent works!

The following codes is misshing, could you share them?  Thank you very much!
https://github.com/futureisatyourhand/issuses-codes/blob/c5a15fe2d5955a6a6862e0c4e07be292573b3eb9/train.py#L28-L29

**Comment by futureisatyourhand** [comment]
I'm sorry, this project I did a few months ago, because the server is broken, a lot of code is missing.
You can refer to  VOCDetection in the voc0712.py file I uploaded to modify it to train the FaceDetection.

**Comment by chenshen03** [comment]
I have run successfully according to the code you uploaded.
Thank you very much.

**Comment by zhuolinumd** [comment]
@chenshen03 @futureisatyourhand Could you share the `FaceDetection` function? Thanks.
