### ISSUE TITLE
Missing modules in train.py

### ISSUE THREAD

**Issue by tkangxun** [futureisatyourhand/issuses-codes#2]
Hi looking through ur code, I notice that there are a few missing modules:

from dataset.voc0712 import FaceDetection
from dataset.data_augment import preproc

**Comment by futureisatyourhand** [comment]
I'm sorry that this is my work a year and a half ago. You can refer to the files  which I upload. data_augment.py is mainly used to processs dataset, you should update according to paper. voc0712.py is helpful for reading information about annotation.
